export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST"
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL"

export const AUTH_LOGIN__REQUEST = "AUTH_LOGIN__REQUEST"
export const AUTH_LOGIN__SUCCESS = "AUTH_LOGIN__SUCCESS"
export const AUTH_LOGIN__FAIL = "AUTH_LOGIN__FAIL"