export const STUDENT_ADD_DATA_REQUEST = "STUDENT_ADD_DATA_REQUEST"
export const STUDENT_ADD_DATA_SUCCESS = "STUDENT_ADD_DATA_SUCCESS"
export const STUDENT_ADD_DATA_FAIL = "STUDENT_ADD_DATA_FAIL"

export const STUDENT_SHOW_REQUEST = "STUDENT_SHOW_REQUEST"
export const STUDENT_SHOW_SUCCESS = "STUDENT_SHOW_SUCCESS"
export const STUDENT_SHOW_FAIL = "STUDENT_SHOW_FAIL"

export const SHOW_SINGLE_STUDENT_REQUEST = "SHOW_SINGLE_STUDENT_REQUEST"
export const SHOW_SINGLE_STUDENT_SUCCESS = "SHOW_SINGLE_STUDENT_SUCCESS"
export const SHOW_SINGLE_STUDENT_FAIL = "SHOW_SINGLE_STUDENT_FAIL"

export const STUDENT_UPDATE_PROFILE_REQUEST = "STUDENT_UPDATE_PROFILE_REQUEST"
export const STUDENT_UPDATE_PROFILE_SUCCESS = "STUDENT_UPDATE_PROFILE_SUCCESS"
export const STUDENT_UPDATE_PROFILE_FAIL = "STUDENT_UPDATE_PROFILE_FAIL"

export const STUDENT_DELETE_PROFILE_REQUEST = "STUDENT_DELETE_PROFILE_REQUEST"
export const STUDENT_DELETE_PROFILE_SUCCESS = "STUDENT_DELETE_PROFILE_SUCCESS"
export const STUDENT_DELETE_PROFILE_FAIL = "STUDENT_DELETE_PROFILE_FAIL"