export { default as Profile } from "./Profile" 
export { default as AddData } from "./AddData" 
export { default as Details } from "./Details" 
export { default as PageNotFound } from "./PageNotFound" 
export { default as Login } from "./Login" 
export { default as Register } from "./Register" 
export { default as MyBooks } from "./MyBooks" 